[alias]

# CHECK
cl = "clippy"
clq = "clippy --quiet"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
bq = "build --quiet"
br = "build --release"
bqb = "build --quiet --bin"
bqe = "build --quiet --example"
brb = "build --release --bin"
bre = "build --release --example"
brqb = "build --release --quiet --bin"
brqe = "build --release --quiet --example"

# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rq = "run --quiet"
rr = "run --release"
rqb = "run --quiet --bin"
rqe = "run --quiet --example"
rrb = "run --release --bin"
rre = "run --release --example"
rrqb = "run --release --quiet --bin"
rrqe = "run --release --quiet --example"

# TEST
t = "test -- --nocapture"
t1 = "test -- --test-threads 1 --nocapture"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"

[build]
# rustdocflags = [ "--html-in-header", "./res/docs-header.html"]
